import Hero from "@/components/Hero";
import Navbar from "@/components/Navbar";
import Slider from "@/components/Slider";
import Footer from "@/components/Footer";
import Quote from "@/components/Quote";
import { SliderData } from "@/components/SliderData";
import Head from "next/head";
import { Aboutme } from "@/components/Aboutme";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar/>
    <Hero/> 
    <Slider slides={SliderData} />
    <Aboutme/>
    <Quote/>
    <Footer/>
    </div>
  );
}
